site_name: Pokie
site_description: Flask boilerplate
strict: true
site_url: https://git.oddbit.org/OddBit/pokie/
repo_name: OddBit/pokie
repo_url: https://git.oddbit.org/OddBit/pokie

theme:
  name: material

nav:
- Overview: index.md
- Introduction:
    - Architecture: tutorial/architecture.md
    - Scaffolding: tutorial/scaffolding.md
    - Tutorial: tutorial/tutorial.md
- Views:
    - Pokie Views: views/index.md
    - REST Views: views/rest.md
    - Controllers: views/controllers.md
plugins:
- search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
